language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py test
  - flake8 .
after_success:
  - coveralls
notifications:
  email:
  - rajat.gupta712@gmail.com
