language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run setup.py test
  - flake8 .
  - coverage report -m
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter
after_success:
  - coveralls
notifications:
  email:
  - rajat.gupta712@gmail.com
